// Generated by CoffeeScript 1.4.0
(function() {

  $(document).ready(function() {
    var layer, rect, stage;
    stage = new Kinetic.Stage({
      container: 'canvas',
      width: $("#canvas").width() - 20,
      height: $("#canvas").height() - 20
    });
    layer = new Kinetic.Layer();
    rect = new Kinetic.Rect({
      x: 239,
      y: 75,
      width: 100,
      height: 50,
      fill: 'green',
      stroke: 'black',
      strokeWidth: 4,
      draggable: true
    });
    layer.add(rect);
    rect.on('mousedown touchstart', function() {
      rect.setFill("blue");
      return layer.draw();
    });
    rect.on('mouseup touchend', function() {
      this.setFill("green");
      return layer.draw();
    });
    return stage.add(layer);
  });

}).call(this);
